controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

detail_room:
    path: '/detailRoom/{name}'
    controller: 'App\Controller\YourControllerName::yourActionMethodName'

